version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./src:/app
      - tmp-data:/app/tmp
    links:
      - db
    tty: true
    stdin_open: true
  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-10080}:80
    volumes:
      - ${PROJECT_PATH:-./src}:/app
      - ./logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ:-Asia/Tokyo}
volumes:
  db-data:
    driver: local
  tmp-data:
  log-data:
